Admin UI
kaaax0815/wg-easy pull request #4
Opened 2024-09-16 14:07 UTC by tetuaoro

todo

2024-09-16 14:16 UTC, kaaax0815 commented
Setup/Migration
Setup/Wireguard (Host, Port)
still missing. If you want I can make the backend logic and a simple ui for it and you can make it better.

Im a little busy rn tho

2024-09-16 15:11 UTC, tetuaoro commented
> Setup/Migration Setup/Wireguard (Host, Port) still missing.

Oh, ok !

2024-09-16 15:57 UTC, kaaax0815 commented
Also there were quite some hydration issues

2024-09-16 16:44 UTC, kaaax0815 commented
If you look in the Developer console you probably have some hydration mismatches

2024-09-18 05:58 UTC, kaaax0815 commented
We have to edit the `localeDetector.ts` as it uses the browser language to try to guess the locale. even tho it should use the database for that.
Or we allow the user to select any language and don't make it fixed

2024-09-18 11:23 UTC, kaaax0815 commented on src/app/pages/setup.vue
> +    name: 'Français',
should probably be `fr`

2024-09-18 11:25 UTC, tetuaoro commented on src/app/pages/setup.vue
> +    name: 'Français',
yeah thx

2024-09-18 13:18 UTC, tetuaoro commented
@kaaax0815 need help with hydration mismatches

### step to reproduce
1. delete container
2. run new container with `docker compose -f *file* up`
3. enter setup page
4. choose a lang (chinese lang for example xD)
5. move toward step
6. reload page

Hydration error occurs

2024-09-18 13:25 UTC, kaaax0815 commented on src/app/pages/setup.vue
> +          <p class="text-lg p-8">{{ $t('setup.msgStepOne') }}</p>
use `text-center` more

2024-09-19 07:35 UTC, kaaax0815 commented
Can't test
```
wg-easy-1  |  ERROR  Vue app aliases are not allowed in server runtime. [importing #build/i18n.options.mjs from node_modules/.pnpm/@nuxtjs+i18n@8.5.1_magicast@0.3.5_rollup@4.21.2_vue@3.4.38_typescript@5.5.4_/node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js]
wg-easy-1  | 
wg-easy-1  | 
wg-easy-1  | [nitro]  ERROR  RollupError: node_modules/.pnpm/@nuxtjs+i18n@8.5.1_magicast@0.3.5_rollup@4.21.2_vue@3.4.38_typescript@5.5.4_/node_modules/@nuxtjs/i18n/dist/runtime/routing/utils.js (2:9): "isRef" is not exported by "virtual:#imports", imported by "node_modules/.pnpm/@nuxtjs+i18n@8.5.1_magicast@0.3.5_rollup@4.21.2_vue@3.4.38_typescript@5.5.4_/node_modules/@nuxtjs/i18n/dist/runtime/routing/utils.js".
wg-easy-1  | 
wg-easy-1  | 
wg-easy-1  | 1: import { isString, isSymbol, isFunction } from "@intlify/shared";
wg-easy-1  | 2: import { isRef, unref } from "#imports";
wg-easy-1  |             ^
wg-easy-1  | 3: export const inBrowser = typeof window !== "undefined";
wg-easy-1  | 4: export function getNormalizedLocales(locales) {
```

2024-09-20 05:52 UTC, kaaax0815 requested changes

2024-09-20 05:52 UTC, kaaax0815 commented on src/app/components/ui/ChooseLang.vue
> +import { LOCALES } from '~/../i18n.config.js';
remove file extension

2024-09-20 05:52 UTC, kaaax0815 commented on src/server/utils/types.ts
> +const { availableLocales } = useI18n();
probably just use exported `LOCALES`

2024-09-28 10:01 UTC, tetuaoro commented
Hi man, how are you today ? I'm on the host/port configuration section today. I'd just like to say that I've run into a problem with the i18n and I don't know why.

When the key/value doesn't exist in another language, the default value (en) seems not to be used by i18n.

2024-09-28 10:22 UTC, kaaax0815 commented
> When the key/value doesn't exist in another language, the default value (en) seems not to be used by i18n.

You have to set the fallback language. https://i18n.nuxtjs.org/docs/guide/locale-fallback

2024-09-29 16:55 UTC, tetuaoro commented
```bash
wg-easy-1  | 2024-09-29T16:54:21.275Z LowDB GET Clients
wg-easy-1  | 2024-09-29T16:54:21.276Z WireGuard Saving Config...
wg-easy-1  | 2024-09-29T16:54:21.276Z WireGuard Config saved successfully.
wg-easy-1  | $ wg-quick down wg0
wg-easy-1  | [nitro] dev:reload: 616.669ms
wg-easy-1  | $ wg-quick up wg0
wg-easy-1  | 
wg-easy-1  |  ERROR  [nitro] [unhandledRejection] Command failed: wg-quick up wg0
wg-easy-1  | [#] 
wg-easy-1  | [#] ip link add wg0 type wireguard
wg-easy-1  | [#] wg setconf wg0 /dev/fd/63
wg-easy-1  | [#] ip -4 address add 10.8.0.1/24 dev wg0
wg-easy-1  | [#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
wg-easy-1  | [#] ip link set mtu 1420 up dev wg0
wg-easy-1  | [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -s fdcc:ad94:bacf:61a4::cafe:0/112 -o eth0 -j MASQUERADE; ip6tables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT;
wg-easy-1  | modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
wg-easy-1  | modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
wg-easy-1  | ip6tables v1.8.10 (legacy): can't initialize ip6tables table nat': Table does not exist (do you need to insmod?)
wg-easy-1  | Perhaps ip6tables or your kernel needs to be upgraded.
wg-easy-1  | [#] ip link delete dev wg0
wg-easy-1  | 
wg-easy-1  | 
wg-easy-1  |   [#]
wg-easy-1  |   [#] ip link add wg0 type wireguard
wg-easy-1  |   [#] wg setconf wg0 /dev/fd/63
wg-easy-1  |   [#] ip -4 address add 10.8.0.1/24 dev wg0
wg-easy-1  |   [#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
wg-easy-1  |   [#] ip link set mtu 1420 up dev wg0
wg-easy-1  |   [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -s fdcc:ad94:bacf:61a4::cafe:0/112 -o eth0 -j MASQUERADE; ip6tables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT;
wg-easy-1  |   modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
wg-easy-1  |   modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
wg-easy-1  |   ip6tables v1.8.10 (legacy): can't initialize ip6tables table nat': Table does not exist (do you need to insmod?)
wg-easy-1  |   Perhaps ip6tables or your kernel needs to be upgraded.
wg-easy-1  |   [#] ip link delete dev wg0
wg-easy-1  |   
wg-easy-1  |   at genericNodeError (node:internal/errors:984:15)
wg-easy-1  |   at wrappedFn (node:internal/errors:538:14)
wg-easy-1  |   at ChildProcess.exithandler (node:child_process:422:12)
wg-easy-1  |   at ChildProcess.emit (node:events:519:28)
wg-easy-1  |   at maybeClose (node:internal/child_process:1105:16)
wg-easy-1  |   at ChildProcess._handle.onexit (node:internal/child_process:305:5)
wg-easy-1  | 
wg-easy-1  | [nitro-runtime] error: 0.132ms
```

2024-09-29 17:02 UTC, kaaax0815 commented
It looks like your kernel modules are somehow broken.

Try
```shell
modprobe ip6_tables
```

Or edit the database and remove iptable scripts as they are not needed for ui development

2024-10-03 15:16 UTC, kaaax0815 commented
@tetuaoro what's your status on this?

2024-10-04 13:31 UTC, tetuaoro commented
> @tetuaoro what's your status on this?

Hi. For now, I can only contribute the week-end.

2024-10-07 06:42 UTC, kaaax0815 commented
> Hi. For now, I can only contribute the week-end.

No problem! Thank you for your help. Highly appreciated.

What in your opinion has to be done still for this pr to be merged?

2024-10-08 14:52 UTC, tetuaoro reviewed
Done

2024-10-09 13:39 UTC, tetuaoro commented
Hi,
I have a question : is a customer also a user ? Do we allow the client (user) to connect to the web interface to retrieve his qrcode himself ?

2024-10-10 07:13 UTC, kaaax0815 commented
@tetuaoro For the migration you could use some of the code I had written here https://github.com/kaaax0815/wg-easy/blob/7a6f7db4d3560f29fb8246b7e6471dfa73edcb30/src/server/utils/config.ts#L12. Maybe users also should be able to pass their old env vars to the ui. my goal is it that users don't have to give out new configs

2024-10-10 07:17 UTC, kaaax0815 commented
> Hi, I have a question : is a client also a user ? Do we allow the client (user) to connect to the web interface to retrieve his qrcode himself ?

no as then you would have to set a password for each peer. and there is unfortunately no way of using the config to authenticate (which would be sick but not possible with own implementations of WireGuard, etc).

The admin can create users in the ui.
Assign groups to users
And assign clients to groups

This is what I thought makes most sense. But I don't know exactly what the users want. Maybe you have a better idea in mind?

2024-10-10 07:20 UTC, kaaax0815 commented
And as you already mentioned in the description checking if a user exists to see if the setup is done is not good.

We should add maybe a setup key to the db. which increments for each step. And also split each step into its own page /setup/1, /setup/2, ... or /setup/general, /setup/user, /setup/migration, .... And then depending on the setup key redirect to the correct page (this would allow for adding more setup steps after the fact; even if user already has a working setup)

This is what I though will work, but maybe you have a better idea

2024-10-10 07:52 UTC, kaaax0815 commented
The Port in the HostPort Section should be supplied by default.
The Text in the Welcome Page should be adjusted the also target new users
The Migration step should be optional or skippable

2024-10-11 08:48 UTC, kaaax0815 commented
I am currently short on time due to another project, but I will be able to contribute more significantly in the coming weeks.

2024-10-11 09:19 UTC, kaaax0815 approved these changes

2024-10-14 09:52 UTC, kaaax0815 commented
Merging so I can work on it

2024-10-14 09:52 UTC, merged